### PR TITLE
Add iOS AppGroup support

### PR DESCRIPTION
**Pull request by heroddaji**
I think current version does not support AppGroup yet, 
So I need it for my work, just try to implement it.

If you think it is good enough, may be can be merged back.
If not, may be suggest me how to improve. 
My first time contribute on github, thank you.

### CODE REVIEW

**Comment by alokrajiv** [comment]
@heroddaji thank you for the PR. I will review and comment. Would love to merge if all test cases pass :)

**Comment by alokrajiv** [comment]
sorry for long wait. can you have a look @GillesC

**Comment by liviublidar** [comment]
How would initWithSuiteName() be  used from JavaScript side? Would calling NativeStorage.initWithSuiteName("someDomain") be enough to instantiate the plugin to work with the specific suite whenever other methods are called?

**Comment by alokrajiv** [comment]
@liviublidar theoretically yes.  Not sure where we are on that feature progress though.

**Comment by alokrajiv** [comment]
@GillesC is this a stable PR? Would it be possible for you to have a look.

Thanks in advance!

**Comment by bkleiner** [comment]
Could this be merged? or are there any outstanding issues?
I need this feature for our current app and i would be happy to help.

**Pull request merged**
