### PR TITLE
Attempting Patch

### PR DESCRIPTION
**Pull request by alokrajiv**
Soln proposed by @sum1190 

Issue #88 

cc @Maziar-Fotouhi 

@GillesC  can you check all test cases.

### CODE REVIEW

**Comment by alokrajiv** [comment]
@GillesC time to merge?

No-one has complained! :)

**Comment by GillesC** [comment]
Let's merge it! :)

**Comment by Maziar-Fotouhi** [comment]
@alokrajiv @GillesC Thanks for your efforts.
Is there going to be an official release with this fix?

**Comment by alokrajiv** [comment]
@Maziar-Fotouhi I think soon we will have to push a new release.

**Pull request merged**
