### PR TITLE
Add keys function to list storage keys

### PR DESCRIPTION
**Pull request by ydeshayes**
Hello, 

I had a keys() function to list all storage keys, because I needed it for redux-persist.

The other workaround for this is to create a 'keys' entry with an array and add the key every time you set an entry and remove it every time you remove an entry but it's i/o consuming.

I used it in iOS only and I can't test it on android or windows for the moment, so feel free to test ! :)

#56

### CODE REVIEW

**Comment by GillesC** [comment]
Thank you for your contribution to the plugin!
I will look into it, when I've got the time :)

**Comment by GillesC** [comment]
Android: **not passed**
Problem: `no suitable method found for success(Object[])
                        callbackContext.success(allEntries.keySet().toArray());`
Maybe you should work with a JSONArray, see the [callbackContext](https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CallbackContext.java).

**Comment by ydeshayes** [comment]
Ok we test on our side in Android. This is the fix https://github.com/TheCocoaProject/cordova-plugin-nativestorage/pull/61/commits/d69c3151ff239d97df7fb57edbd296d4028fdf35

**Comment by GillesC** [comment]
Question: Is the result (from the success callback) of the same type on all platforms. Because I see that in iOS the message is sent as a String. In Android, the result is returned as a JSONArray. It would be better to provide the result in a uniform manner.

**Comment by ydeshayes** [comment]
I retrieved the keys as Array already because I think there is an eval going on between the cordova exec and the javascript context. But I've fixed the code to explicitly messageAsArray the result on Ios.

**Comment by GillesC** [comment]
Thank you for your contribution, you may include yourself in the [contributor list](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/blob/master/package.json).

**Comment by alokrajiv** [comment]
Attempted fix in PR #81

**Pull request merged**
