### PR TITLE
add support for windows10 platform

### PR DESCRIPTION
**Pull request by 3h3c**

### CODE REVIEW

**Comment by GillesC** [comment]
Could you proivide me some info, about what you've just done?
Because I'm not a Windows 10 dev.
For instance, I see a `vault` var, does this mean the stored value is encrypted in any way?

**Comment by 3h3c** [comment]
hey,

The PasswordVault lets application to store and retrieve user’s credentials in a secure way: all password are encrypted and cannot be accessed by other applications.

see: https://msdn.microsoft.com/de-de/library/windows/apps/windows.security.credentials.passwordvault.aspx

**Comment by GillesC** [comment]
I'll test your PR, if everything is OK. I'll merge it.

**Comment by alokrajiv** [comment]
Is the test suite passing?

**Comment by GillesC** [comment]
I'm installing the requirements for testing on Windows 10 :) I'll check the other platforms now.

**Comment by GillesC** [comment]
@3h3c  When building the demo application (from the cordova CLI)  I get the following error:
`Error: Properties.PublisherDisplayName elements must be non-empty in appxmanifest at undefined`

**Comment by GillesC** [comment]
Android & browser passed the test.

**Comment by 3h3c** [comment]
hey,

any new news?

**Comment by GillesC** [comment]
I've installed VS 2015.
But I'm unable to run our test suite.
The following error occured: "Error: Properties.PublisherDisplayName elements must be non-empty in appxmanifest at undefined"

Extra info: command was "cordova run windows", and I had an available windows device "Available windows devices: 0. Device (device)".

**Comment by 3h3c** [comment]
try to build it with:

cordova build windows --arch="x86"
and run with cordova run windows --arch="x86"

**Comment by GillesC** [comment]
I got the same result:
image

**Comment by 3h3c** [comment]
you have to change your config.xml.

add these lines:

<author email="example@example.com" href="http://example.com/">
 +        Example Company
 +    </author>

**Comment by GillesC** [comment]
Windows: not passed

Things to do:

- implementing correct error objects
- getInt returns string instead of number

Please see [this section](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#demo-example) to test your implementation. Change the git clone to your repo.

**Comment by GillesC** [comment]
Errors thrown because of 'Encryption' tests, can be disgarded because it isn't implemented in iOS. And Windows functionality has priority. So the only errors you can have are these related to the encryption methods.

**Comment by GillesC** [comment]
[Commit ](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/pull/38/commits/83f2993fa0c105a01e1e54e6b0bd1590da84081b) not confirmed. 
The returned value is now `undefinied`. (`Error: Expected undefined to equal 154243`)

**Comment by alokrajiv** [comment]
Are the tests passing? You merged it?

**Comment by GillesC** [comment]
Tests have passed, and it's merged! :)

**Comment by GillesC** [comment]
Gonna publish it to NPM now.

**Comment by GillesC** [comment]
Published on NPM

**Pull request merged**
